### ISSUE TITLE
Define and setup new environments for development, testing, staging, production

### ISSUE THREAD

**Issue by 2075** [playzero/zero-network#102]
Define and setup new environments for development, testing, staging, production
We want to maintain different environments with different qualities of service:

- [ ] draw and discuss in figma during architecture session

assumptions:

development — can break, could work
- `dev` and below

testing — can break, should work
- `test`, `mock test`

approval — should work
- `staging`

live — must work
- `alphaville` standalone releay/parachain with stable environment
- `rococo` parachain
- `production` parachthread connected to polkadot

**Comment by vovacha** [comment]
Closing this as a duplicate.
