### ISSUE TITLE
add rmrk2 pallets to parachain

### ISSUE THREAD

**Issue by vayesy** [playzero/zero-network#119]
Add Rmrk pallet (https://github.com/rmrk-team/rmrk-substrate) to the parachain runtimes and make it's extrinsics callable.

**Comment by vasylenko-yevhen** [comment]
Since Rmrk has no version 0.9.25 available, we have to update version of our chain source code from 0.9.25 to 0.9.28. 
So this task is currently on hold intil upgrade is done.

**Comment by vasylenko-yevhen** [comment]
#122 related issue.
