### ISSUE TITLE
Reduce block time for subzero parachain runtime

### ISSUE THREAD

**Issue by vovacha** [playzero/zero-network#168]
New block time is 6 sec.

**Comment by vovacha** [comment]
> thanks for that, so will we do something like dev 3s test, stage 6s live tbd ?s

Doing this way, we need different runtimes for each env.
We already have 3 to support: standalone, subzero, zero. Adding more runtimes to support will increase complexity.

**Comment by 2075** [comment]
that's why we discussed a setup with nodes and runtimes separated, but yes, let's stick to 63 for dev up to staging and discuss later if we want/need 12s for prod.

**Comment by vovacha** [comment]
@2075 The block time for all parachains is currently restricted to 12 sec because of consensus implementation in the relay chain. So, for prod 12 sec is not even a discussion. But from the recent news I read that soon, the block time will be reduced to 6 sec.
That's also why I thought that even for dev env we could have some issues with changing it. Maybe `rococo-local` runtime should be changed as well.
@vayesy WDYT?

**Comment by vayesy** [comment]
@vovacha looks you are right - with current consensus implementation parachain block is included after 2 blocks in the relay chain, which is 12 seconds. There's no easy way to change that for dev environment even if we'll manage to update block time constant on the forked relay chain source code, it will still require additional changes in regards to consensus algorithm.
Additional links:
- https://substrate.stackexchange.com/a/4457 - similar questions raised before
- https://github.com/paritytech/polkadot/issues/3779 - issue to implement asynchronous block inclusion, which will allow to use faster block times on the parachains.

**Comment by vovacha** [comment]
I am closing the issue since it's not possible to change the block time at the moment.
