### ISSUE TITLE
Deploy Runtime Version 63

### ISSUE THREAD

**Issue by 5-mark** [playzero/zero-network#199]
### What needs to be done

- Deploy latest chain changes on dev. 
- Ensure Squid is supporting version 63 and 62  

### Why it needs to be done**

so that we can test the latest changes of the chain and release to stage afterwards. 

### Acceptance Criteria/Task List**

- [ ] latest version 63 deployed on dev
- [ ] all assigned tickets can be tested

### Additional context
none

**Comment by vovacha** [comment]
Deployed on dev env.

**Comment by 2075** [comment]
changelog would be also good
