### ISSUE TITLE
create infrastructure for ZERO runtime test environment

### ISSUE THREAD

**Issue by 5-mark** [playzero/zero-network#208]
## User Story
As developer I want to have a proper test environment for the ZERO runtime so I can deploy on it. 

## Acceptance Criteria

1. create infrastructure 
2. create docker compose for swarm
3. update big repo
4. update portainer with this new environment

## Additional Information

- relates to EPIC #203

## How to test

1. environment ready to be deployed

**Comment by 2075** [comment]
@vovacha any updates ?
