### ISSUE TITLE
Create `battlepass` pallet

### ISSUE THREAD

**Issue by vayesy** [playzero/zero-network#227]
### What needs to be done
Create `Battlepass` pallet with basic support for battlepass functionality.

### Acceptance Criteria/Task List**
Next extrinsics should be created:
- [x] create_battlepass
- [x] claim_battlepass

#### create_battlepass - extrinsic to create battle pass for organization.
Parameters:
  * origin - should be one of: sudo, org prime
  * org_id - organization id to create battlepass for
  * price - price to pay for the user to get access to battle pass
  * cid - content id
  
Outcome:
Battlepass entity created onchain with given parameters (org_id, price, cide). Later this entity will be used to track battlepass progress.

#### claim_battlepass - extrinsic to get access to existing battlepass for the user, who wants to participate
Parameters:
  * origin - user which wants buys battlepass
  * org_id - organization id, which battlepass belongs to
  * battlepass_id - battlepass id
  * discord_id _[optional]_ - discord id for the user, if any
  * payment_id _[optional]_ - external id for the payment, made by the user
  
Outcome
NFT is generated and assigned to the user, granting access to the battlepass, it was requested for.
In future it will allow user to finish tasks, earn points and claim battlepass rewards with those points.

**Comment by 2075** [comment]
- why price? do you want to settle the stripe payment via oracle? would be perfect but harder than what was asked for today
- also you may need an accepted currency to settle

we also had these thoughts for the general macro view:
![image](https://user-images.githubusercontent.com/1140449/207589900-05b21e5a-ea70-44f8-bdee-63e04cbf24a8.png)

**Comment by vayesy** [comment]
@2075 We didn't plan to use price in any way at the moment. Just store it for future. But we may also skip it for now.
Apart from that, if everything looks good @FiberMan starts to work on the implementation.

**Comment by vayesy** [comment]
Should we use gamedao-protocol or zero-network repo to create this pallet in?

**Comment by 2075** [comment]
it belongs to gamedao, so should be there imho, let's ship it

**Comment by 2075** [comment]
any update here? @FiberMan 

btw we can also use uniques pallet if we decide to.

**Comment by FiberMan** [comment]
PR: https://github.com/gamedaoco/gamedao-protocol/pull/120
