### ISSUE TITLE
dev/test graph and chain not in sync

### ISSUE THREAD

**Issue by 2075** [playzero/zero-network#234]
data on chain does not seem to be indexed on test and dev graph

<img width="2663" alt="image" src="https://user-images.githubusercontent.com/1140449/209481499-1775973c-e8bc-4147-b26b-1ea72f6d413d.png">

**Comment by vovacha** [comment]
This is a discussion created for this topic: [https://github.com/playzero/zero-network/discussions/200](https://github.com/playzero/zero-network/discussions/200)
