### ISSUE TITLE
rococo onboarding

### ISSUE THREAD

**Issue by 2075** [playzero/zero-network#33]
Required steps to get Rococo slot:
- [x] Acquire ParaId in Rococo network.
- [x] Add parachain details to polkadot ui app.
- [x] Create issue requesting Rococo slot.

**Comment by vovacha** [comment]
@vasylenko-yevhen could you take this, update acceptance criteria and write current status?

**Comment by 2075** [comment]
bump :) @vasylenko-yevhen

**Comment by vasylenko-yevhen** [comment]
- Acquired ParaId: 4040
- Polkadot UI PR link https://github.com/polkadot-js/apps/pull/7919
- Rococo issue link https://github.com/paritytech/subport/issues/423
- Parachain WS endpoint: `wss://staging.para.sub.zero.io/`

Subzero parachain now active and is part of Rococo ecosystem.
