### ISSUE TITLE
Deploy the latest 3.1.58 release for the Beeblebrox test env

### ISSUE THREAD

**Issue by vovacha** [playzero/zero-network#72]
Planned for 26.06

**Comment by vasylenko-yevhen** [comment]
Updated beeblebrox with latest version.
https://polkadot.js.org/apps/?rpc=wss://beeblebrox.zero.io/node
![image](https://user-images.githubusercontent.com/7493662/181079862-abca060e-ca97-4c6f-b017-4950bdc680bb.png)

**Comment by vasylenko-yevhen** [comment]
Temporarily rolled back to old version of the chain. Once Graph support is implemented, will switch back.
